In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score



import tensorflow as tf
from tensorflow  import keras as k
from tensorflow.keras import backend as K
from tensorflow.keras.utils import to_categorical


# load the dataset

In [2]:
dataset= pd.read_csv("1.csv");  # load the  dataset

In [3]:
dataset

0  1502  2215  2153  1
0            1.0  1667  2072  2047  1
1            2.0  1611  1957  1906  1
2            3.0  1601  1939  1831  1
3            4.0  1643  1965  1879  1
4            5.0  1604  1959  1921  1
...          ...   ...   ...   ... ..
162495  162500.0  1927  2388  2074  7
162496  162500.0  1930  2383  2074  7
162497  162500.0  1929  2385  2076  7
162498  162500.0  1926  2385  2078  7
162499  162500.0  1922  2387  2078  0

[162500 rows x 5 columns]

# Preprocessiong 

In [4]:
dataset=dataset.drop(['0'], axis=1)   # the dataset has the index 0 is columns that why remove that

In [5]:
dataset

1502  2215  2153  1
0       1667  2072  2047  1
1       1611  1957  1906  1
2       1601  1939  1831  1
3       1643  1965  1879  1
4       1604  1959  1921  1
...      ...   ...   ... ..
162495  1927  2388  2074  7
162496  1930  2383  2074  7
162497  1929  2385  2076  7
162498  1926  2385  2078  7
162499  1922  2387  2078  0

[162500 rows x 4 columns]

In [6]:
dataset.describe()    # describe the quatriles ,how the features are the scaled ,class is balanced or not

1502           2215           2153              1
count  162500.000000  162500.000000  162500.000000  162500.000000
mean     1910.673372    2380.287385    2041.214142       4.899705
std        40.640690      41.923851      59.528943       2.424299
min      1455.000000    1697.000000    1644.000000       0.000000
25%      1886.000000    2374.000000    1991.000000       3.000000
50%      1905.000000    2381.000000    2022.000000       7.000000
75%      1935.000000    2386.000000    2101.000000       7.000000
max      2356.000000    2713.000000    2739.000000       7.000000

In [7]:
dataset.isnull()    #checking the values that dose the dataset have the null values or not

1502   2215   2153      1
0       False  False  False  False
1       False  False  False  False
2       False  False  False  False
3       False  False  False  False
4       False  False  False  False
...       ...    ...    ...    ...
162495  False  False  False  False
162496  False  False  False  False
162497  False  False  False  False
162498  False  False  False  False
162499  False  False  False  False

[162500 rows x 4 columns]

In [8]:
dataset.info()   # checking the type of the of the feature that all the feature has the same type or not

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162500 entries, 0 to 162499
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   1502    162500 non-null  int64
 1   2215    162500 non-null  int64
 2   2153    162500 non-null  int64
 3   1       162500 non-null  int64
dtypes: int64(4)
memory usage: 5.0 MB


# Seperating the dependent and independet variables

In [9]:
X=dataset.iloc[:,:3].values
Y=dataset.iloc[:,3:4].values

In [10]:
print(X.shape)  ##checking the size of the columns are same 
print(Y.shape)

(162500, 1)

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=.20)   #split the dataset into traning and testing dataset  so that ML model validate

# standard scaler normalize the feature so that all the feature on the same scale

In [12]:
sc=StandardScaler()
train_x=sc.fit_transform(xtrain)
test_x=sc.fit_transform(xtest)

In [108]:
print(test_x[0])

[ 0.33004921 -1.59050139 -0.28765847]


# KNeighbors classifier supervised algorithm

In [13]:
classifier=KNeighborsClassifier(n_neighbors=5)   #n_neighbors is hyperparamenter 

In [14]:
classifier.fit(train_x,ytrain.ravel())  #tranning the model

KNeighborsClassifier()

In [15]:
ypre=classifier.predict(test_x)  ## testing the model

In [16]:
print(confusion_matrix(ytest,ypre)) # confusion matrics which helps to tell the  performace   about the model 

[[ 6420     4     3    97    19     0   116]
 [    9    26     6    99     3     1    57]
 [    7     8   767   165    15    13  1265]
 [  154    25   102  4394    81    30   517]
 [   25     2     6   297   215     9    95]
 [    7     3    47   383    12    28   108]
 [  148    33   635   507    27    30 15480]]


In [17]:
print(classification_report(ytest,ypre))   # the acuracy of the model is 84% whcih quite amazing

              precision    recall  f1-score   support

           1       0.95      0.96      0.96      6659
           2       0.26      0.13      0.17       201
           3       0.49      0.34      0.40      2240
           4       0.74      0.83      0.78      5303
           5       0.58      0.33      0.42       649
           6       0.25      0.05      0.08       588
           7       0.88      0.92      0.90     16860

    accuracy                           0.84     32500
   macro avg       0.59      0.51      0.53     32500
weighted avg       0.82      0.84      0.83     32500



# Decision tree 2 supervised machine learnnin algorithm

In [18]:
DT=DecisionTreeClassifier(criterion="gini",random_state=42)   # criterion  is the hyperparamerter and random state 

In [19]:
DT.fit(train_x,ytrain)  # traning the model


DecisionTreeClassifier(random_state=42)

In [20]:
ypre1=DT.predict(test_x)   ## test the model on the test data

In [21]:
print(accuracy_score(ytest,ypre1))  # the accuracy of the model is 78% which is less then KNN model

0.7805538461538462


# Neural network 
is this neural network

In [99]:
model = k.Sequential([
    
    k.layers.Dense(512,activation='relu', input_shape=(xtrain.shape[1],)),

    k.layers.Dense(256, activation='relu'),
    k.layers.BatchNormalization(),
    k.layers.Dropout(0.2),

    k.layers.Dense(128, activation='softmax'),
    k.layers.Dense(1,activation='sigmoid'),
])


model.compile(
    optimizer=k.optimizers.Adam(),
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_100 (Dense)            (None, 512)               2048      
_________________________________________________________________
dense_101 (Dense)            (None, 256)               131328    
_________________________________________________________________
batch_normalization_42 (Batc (None, 256)               1024      
_________________________________________________________________
dropout_31 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_102 (Dense)            (None, 128)               32896     
_________________________________________________________________
dense_103 (Dense)            (None, 1)                 129       
Total params: 167,425
Trainable params: 166,913
Non-trainable params: 512
_____________________________________________

In [85]:
list1=np.unique(ytrain)
print(list1)   #number of classes in the dataset

[0 1 2 3 4 5 6 7]


# weights initilization

In [86]:
train_class_weights={0: 1.0,
            1: 10.5, 
            2: 4.8,
            3: 29.5,
            4: 36.4,
            5:32,
            6:44,
            7:30}

#  epoxhs are iteration  ->hyperparameter

In [104]:
epochs = 10
history = model.fit(
                    train_x, ytrain, 
                    epochs=epochs
                   )

Epoch 1/10
4063/4063 [==============================] - 7s 2ms/step - loss: -331.9525 - accuracy: 0.2078
Epoch 2/10
4063/4063 [==============================] - 7s 2ms/step - loss: -363.4693 - accuracy: 0.2078
Epoch 3/10
4063/4063 [==============================] - 7s 2ms/step - loss: -394.9255 - accuracy: 0.2078
Epoch 4/10
4063/4063 [==============================] - 7s 2ms/step - loss: -426.3522 - accuracy: 0.2078
Epoch 5/10
4063/4063 [==============================] - 7s 2ms/step - loss: -457.8440 - accuracy: 0.2078
Epoch 6/10
4063/4063 [==============================] - 6s 2ms/step - loss: -489.2971 - accuracy: 0.2078
Epoch 7/10
4063/4063 [==============================] - 7s 2ms/step - loss: -520.7792 - accuracy: 0.2078
Epoch 8/10
4063/4063 [==============================] - 7s 2ms/step - loss: -552.2316 - accuracy: 0.2078
Epoch 9/10
4063/4063 [==============================] - 6s 2ms/step - loss: -583.6938 - accuracy: 0.2078
Epoch 10/10
4063/4063 [==============================] 

In [112]:
x=0.33004921
y=-1.59050139
z=-0.28765847
predict=model.predict(x,y,z)

IndexError: list index out of range